# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    serializer:
        serialize_null: true
    format_listener:
        rules:
              - { path: '^/', priorities: ['json'], fallback_format: 'json' } #dans la video le dernier json n'est pas entre guillemet
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: true
    
    view:
        formats: { json: true, xml: false, rss: false } #Dans la vidéo 
        view_response_listener: true 
        mime_types:
            json: ['application/json', 'application/json;version=1.0']
    versioning:
        enabled: true
        resolvers:
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    exception:
        enabled: true
        codes:
            App\Exception\ResourceValidationException: 400 
        messages:
            App\Exception\ResourceValidationException: true
        exception_controller: 'fos_rest.exception.controller:showAction'
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }

    